/*
 * generated by Xtext
 */
package org.eclipse.xpect.tests;

import org.eclipse.xpect.ui.internal.XpectActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

import com.google.inject.Injector;

public class XpectUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return XpectActivator.getInstance().getInjector("org.eclipse.xpect.Xpect");
	}

}