/*
 * generated by Xtext 2.31.0
 */
package org.eclipse.xpect.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xpect.XpectRuntimeModule;
import org.eclipse.xpect.XpectStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class XpectIdeSetup extends XpectStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new XpectRuntimeModule(), new XpectIdeModule()));
	}
	
}
